# render.yaml
services:
  - type: web
    name: question-backend
    env: python
    buildCommand: pip install -r Question_Generator/requirements.txt
    startCommand: uvicorn Question_Generator.app:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: PORT
        value: 10000
